config/routes.rb
Cms::Application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Cms::API => '/'
  
  get '/admin/home', to: 'admin#home'
  get '/admin/page', to: 'admin#page'
  get '/admin/login', to: 'admin#login'
  post '/admin/authen', to: 'admin#authen'
  # get '/admin/authen', to: 'admin#authen'
end

app/models/api_key.rb
class ApiKey < ApplicationRecord

    before_create :generate_access_token
    before_create :set_expiration
    belongs_to :member
  
    def expired?
      DateTime.now.utc >= self.expires_at
    end
  
    def expired
      self.expires_at = DateTime.now.utc
    end
  
    private
  
    def generate_access_token
      begin
        self.access_token = SecureRandom.hex
      end while self.class.exists?(access_token: access_token)
    end
  
    def set_expiration
      self.expires_at = DateTime.now.utc + 30.minutes
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
    has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

    before_action :find_token, :only => [:home, :page]
    skip_before_action :verify_authenticity_token

    attr_reader :token, :header

    def home
        @header = "Home"
        @contents = "Welcome setting Page"
        render layout: "layout_admin"
    end

    def page
        @header = "Page"
        render layout: "layout_admin"
    end

    def login

    end

    def authen
        respon = admin_authentication(params)
        @token = respon[:token]

        redirect_checker
    end
 
    private

    def redirect_checker
        redirect_to admin_home_path if @header == "Home" || @header == nil
        redirect_to admin_page_path if @header == "Page"
    end

    def admin_authentication(params)
        Admin::AdminAction.new.authentication(params)
    end

    def find_token
        if @token == nil 
            @token = ApiKey.last.access_token
        end

        if !Admin::AdminAction.new.check_token(@token) 
            redirect_to admin_login_path
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home.html.erb
<h1> <%= @contents%> </h1>

app/views/admin/login.html.erb
<!-- 
<dialog class="mdl-dialog">
    <h4 class="mdl-dialog__title">Authentication</h4>
    <div class="mdl-dialog__content">
        <p>Please your enter username and password.</p>
        <form action="<%= admin_authen_path %>" method="post">
            <div class="mdl-textfield mdl-js-textfield">
                <input class="mdl-textfield__input" type="text" id="sample1" name="username">
                <label class="mdl-textfield__label" for="sample1">Username...</label>
            </div> 
            <div class="mdl-textfield mdl-js-textfield">
                <input class="mdl-textfield__input" type="password" id="sample2" name="password">
                <label class="mdl-textfield__label" for="sample1">Password...</label>
            </div>  
            <div class="mdl-dialog__actions">
                <button type="button" class="mdl-button" type="submit">Ok</button>
                <button type="button" class="mdl-button close">Cancel</button>
            </div>
             



        </form>
    </div>
</dialog>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <script>
    
                var dialog = document.querySelector('dialog');
                dialog.showModal();
            
                dialog.querySelector('.close').addEventListener('click', function() {
                    dialog.close();
                });
            </script>
            -->

<div class="modal fade"  id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/admin/authen" method="post">
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Username:</label>
                        <input type="text" class="form-control" name="username" id="username">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Password:</label>
                        <input type="password" class="form-control" name="password" id="password">
                    </div>
                
            </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Register</button>
            <button class="btn btn-primary" type="submit" >Ok</button>
            
            <%# <%= button_to "OK", admin_authen_path(username: name[:username] , password: :password), :id => "open-contacts-dialog-btn", %>
                <%# :class => "btn btn-primary",:method => :post %> 
        </form>
        </div>
        </div>
    </div>
</div>

<script>

    $('#exampleModal').modal({focus: true}).on('shown.bs.modal', function (event) {
        focus:true;
        var button = $(event.relatedTarget) // Button that triggered the modal
        var recipient = button.data('whatever') // Extract info from data-* attributes
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        
        var modal = $(this)
        })
 </script>

app/views/admin/page.html.erb
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--6-col">
        <h1><%= @header %></h1>
    </div>
    <div class="mdl-cell mdl-cell--4-col"></div>
    <div class="mdl-cell mdl-cell--2-col">
        <br><br>
        <button class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
            <i class="material-icons">add</i>
        </button>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <%# <link rel="stylesheet" href="/mdl/material.css">  %>
    <%# <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>Admin</title>

  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <%# <script  src="/mdl/material.js"></script> %>
    <%= yield %>
  </body>
</html>

app/views/layouts/layout_admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="/mdl/material.css"> 
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <title>Admin</title>
</head>

<body>

   <!-- No header, and the drawer stays open on larger screens (fixed drawer). -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Admin</span>
            <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href=<%= admin_home_path%>> Home </a>
            <a class="mdl-navigation__link" href=<%= admin_page_path%>> Page</a>
            <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Link</a>
            </nav>
        </div>
        <main class="mdl-layout__content">
            <div class="page-content">
                <%= yield %>
            </div>
        </main>
    </div>
</body>
</html>